### PR TITLE
Preact+Webpack update + misc

### PR DESCRIPTION
**Pull request by brandonkal**
A bundle of updates.

I had to solve the issue of FOUC so I could continue to use this extension. In the process, I upgraded dependencies and fixed spelling errors.

~I haven't bothered upgrading ESLint. It is currently trying to parse JSON as JS.~

Now upgraded!

### CODE REVIEW

**Comment by brandonkal** [comment]
Please merge this. Tested it and it fixes the flash of content on navigation.

**Comment by johnmee** [comment]
Thanks Brandon.  Although `npm install` it today flags 87 vulnerabilities of which `npm audit fix` resolves all but 5 of them.

**Comment by brandonkal** [comment]
```
$ npm audit
found 0 vulnerabilities
```

I've updated to Preact X.
All packages are now updated with the exception of the component library. That should be a seperate PR.

@johnmee @eejdoowad

Ready for review. I've been using my fork for a long time, so it would be great to see this finally merged in!

**Comment by brandonkal** [comment]
Oops. I see on a fresh install the menu is empty. I believe I had this issue last time which is why I didn't go to Preact X. If you guys have pointers why this could be happening that would help.

**Comment by brandonkal** [comment]
Alright. The issues are sorted and everything is now working with Preact X! Ready for review and merge.

**Comment by eejdoowad** [comment]
That's a massive update! Thanks for taking the time to upgrade dependencies, refactor code, fix major bugs, and add new features. I've reviewed the file changes and tested the updates on Firefox and Chrome, and everything checks out.

I'm merging this change now, but a production release will be delayed until I resolve a bug that breaks settings when the extension updates.

**Comment by brandonkal** [comment]
Glad to see this merged @eejdoowad 
Do you have the update issue in the tracker?

**Comment by eejdoowad** [comment]
Just made one: #287. I haven't had a chance to work on it. It will probably be a challenging bug to replicate/resolve. Do you want to try tackling it? Otherwise I'll give it a shot this weekend.

**Comment by brandonkal** [comment]
Thanks. I'm not able to reproduce that so it would be better if you worked on it.

**Pull request merged**
